baseURL = "https://www.bianzhifu.com/"
languageCode = "en-us"
title = "BianZhifu"
theme = "LeaveIt"
paginate = 10
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true
[Permalinks]
  posts = "/:year/:filename/"
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "AriaNg"
    url = "/ariang/"
    weight = 5
[params.social]
  Email   = "bianzhifu@gmail.com"
  GitHub = "bianzhifu"
  Telegram = "bianzhifu"
  Twitter = "bianzhifu"
  Facebook = "bianzhifu"
[params]
  since = 2012
  author = "BianZhifu"
  avatar = "https://cdn.v2ex.com/gravatar/cc462fdca5d0bc0f512069128a61ec52"
  subtitle = "要么旅行，要么读书，身体和灵魂必须有一个在路上。"
  cdn_url = ""           # Base CDN URL
  home_mode = "" # post or other
  google_verification = ""
  description = "" # site description
  keywords = "" # site keywords
  beian = ""
  baiduAnalytics = ""
  license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'